### ISSUE TITLE
0704版本，卡在登录界面不动了

### ISSUE THREAD

**Issue by mapleshadow** [TechXueXi/TechXueXi#1]
如题，扫了二维码之后，就卡在界面不动了

**Comment by pkusocold** [comment]
SourcePackages\pdlearn\mydriver.py title_of_login函数里面改为is_title1 = bool(EC.title_is(u'我的学习')(driver))就可以运行了

**Comment by CRYSTER12** [comment]
mydriver.py中第29行  u'我的学 xi '  改为 u'我的学习'

**Comment by tchxiyi** [comment]
已经提交到dev分支了,谢谢小伙伴们帮助解决这个问题，爱你们，喵~
