### ISSUE TITLE
树莓派3b运行提示tail: cannot read realtime clock: Operation not permitted

### ISSUE THREAD

**Issue by hupo376787** [TechXueXi/TechXueXi#130]
### 清单

- [x] 我已经仔细阅读过 README.md  ( https://github.com/TechXueXi/TechXueXi/blob/developing/README.md )
- [x] 我已经仔细阅读过 文档  ( https://github.com/TechXueXi/TechXueXi/wiki )
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [ ] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：

**软件/源码版本**：

**浏览器、驱动版本**：

**python版本**：

**docker版本**：

-----

## 详细描述
答：

## 全部报错
答：

```
i@raspberrypi:~/www/xuexi $ docker-compose up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
techxuexi-web is up-to-date
Attaching to techxuexi-web
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
techxuexi-web | 开始运行
techxuexi-web | tail: cannot read realtime clock: Operation not permitted
techxuexi-web exited with code 1

```

## 建议
答：

**Comment by hao14293** [comment]
在 docker run 后面加上 --privileged
```sh
docker run --privileged
```

**Comment by Eraaa** [comment]
> ### 清单
> * [x]  我已经仔细阅读过 README.md  ( https://github.com/TechXueXi/TechXueXi/blob/developing/README.md )
> * [x]  我已经仔细阅读过 文档  ( https://github.com/TechXueXi/TechXueXi/wiki )
> * [x]  我已经查看/搜索过所有已有 issue，无论是open还是close的
> * [x]  我已经通过搜索引擎搜索   [www.google.com](http://www.google.com)  [www.baidu.com](http://www.baidu.com)
> * [ ]  我已经到提供的在线聊天室询问过  (聊天室说明：[交流群（在线聊天室）地址及说明  #14](https://github.com/TechXueXi/TechXueXi/issues/14))
> 
> **系统版本，包含位数**：
> 
> **软件/源码版本**：
> 
> **浏览器、驱动版本**：
> 
> **python版本**：
> 
> **docker版本**：
> 
> ## 详细描述
> 答：
> 
> ## 全部报错
> 答：
> 
> ```
> i@raspberrypi:~/www/xuexi $ docker-compose up
> Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
> techxuexi-web is up-to-date
> Attaching to techxuexi-web
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web | touch: setting times of '/var/log/cron.log': Operation not permitted
> techxuexi-web | 开始运行
> techxuexi-web | tail: cannot read realtime clock: Operation not permitted
> techxuexi-web exited with code 1
> ```
> 
> ## 建议
> 答：

不知道，你这种情况解决了吗？  我用是玩客arm32v7的系统，也出现同样的问题。
