### ISSUE TITLE
mac m1 conda python3.8 环境下报错

### ISSUE THREAD

**Issue by Seannnnnnnion** [TechXueXi/TechXueXi#132]
Unable to find zbar shared library

**Comment by techxuexi21** [comment]
@Seannnnnnnion 文档里，和之前的issue里都有，要安装

**Comment by niupuyue** [comment]
我也遇到了这个问题，Zbar，扫描二维码的库在mac中无法安装。文档还issue有提到过吗？麻烦给个链接。谢谢~

**Comment by techxuexi21** [comment]
https://github.com/TechXueXi/TechXueXi/issues/50

https://github.com/TechXueXi/TechXueXi/issues/80

**Comment by niupuyue** [comment]
https://www.tinkol.com/372   这里面有提到这个问题。因为我用了清华大学的镜像，目前清华大学的镜像中依然是指向到bintray的，所以也跟着404了。所以要解决问题，那就是去掉清华大学的镜像设置就好了。翻墙，然后把brew的地址设置为默认地址，重新执行brew update和brew upgrade，然后在执行brew install zbar ,问题解决。。。我爱学习！

**Comment by Seannnnnnnion** [comment]
突然发现我是科大的镜像源地址
