### ISSUE TITLE
"https://github.com.cnpmjs.org/TechXueXi/TechXueXi.git"已被举报

### ISSUE THREAD

**Issue by azoth07** [TechXueXi/TechXueXi#145]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

latest

### 系统版本，包含位数

centos7.8 x64

### 浏览器、驱动版本

chrome v73.0.0 + chromedriver v x.x.x

### python版本

 python3.6.8 x32

### docker tag版本

latest

### 推送方式

5 telegram

### 详细描述

docker 编译会出问题，"https://github.com.cnpmjs.org/TechXueXi/TechXueXi.git"已被举报，Could not resolve host: github.com.cnpmjs.org
![image](https://user-images.githubusercontent.com/7674044/153322509-46b7c13a-a159-4edf-b160-22e2c4aa21c8.png)

**Comment by arenekosreal** [comment]
这个是 cnpmjs.org 的原理导致的。目前为止很多镜像站的原理都是反向代理，然后因为返回的网页和 GitHub 一样，地址与 github.com 相似，但地址不是 github.com 而被认为是虚假网站。详细信息里面可以选择继续访问，也可以在浏览器设置里面关掉Smartscreen 但不建议。另外这不影响 git 程序克隆仓库。

**Comment by techxuexi21** [comment]
俺刚才换了一下。可以使用的代理有：

https://hub.fastgit.xyz

https://github.com.cnpmjs.org

https://gitclone.com

后续计划增加 多个镜像优选 https://github.com/orgs/TechXueXi/projects/2#card-77477297

环境变量里面有一个-sourcepath=

可以修改

docker run时候加一个-e “sourcepath=xxxx”

或者compose文件environment里面加一个- sourcepath=xxxx

**Comment by azoth07** [comment]
good job~

**Comment by lisonglin980** [comment]
> 俺刚才换了一下。可以使用的代理有：
> 
> https://hub.fastgit.xyz
> 
> https://github.com.cnpmjs.org
> 
> https://gitclone.com
> 
> #2计划增加2个优先计划[https://github.com/orgsTechXueXi/projects/projectscard
> 或者compose文件环境里面加一个-sourcepath=xxxx

您好，我是微信更新失败，尝试在docker-compose文件的环境变量environment:后面添加
- Sourcepath=https://gitclone.com/TechXueXi/TechXueXi.git依然提示更新失败，请问下代理后面的仓库地址应该填的是什么呢，尝试过把gitclone.com这个github代理我改成自建的也是更新失败

**Comment by ixmu** [comment]
大佬是否可以替换镜像中的github.com.cnpmjs.org地址，换成github或者其他加速源
