### ISSUE TITLE
docker版登录卡住

### ISSUE THREAD

**Issue by zlhdd108** [TechXueXi/TechXueXi#15]
**系统版本，包含位数**：
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:45 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
**python版本**：
Python 3.7.3
**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：docker版用老的代码可以正常运行，虽然会卡专项答题；新的代码，发送url到钉钉后，也点击登录了，但是并没有往下走；稍后的超时重新发送url也会报错

## 全部报错
答：

```
私はChina を愛しています
```
![image](https://user-images.githubusercontent.com/16465666/124379987-ebb78e80-dcec-11eb-8a25-c971d35703f0.png)

## 建议
答：

**Comment by mapleshadow** [comment]
PC版也卡登陆界面，看来是代码出问题了

**Comment by zlhdd108** [comment]
> PC版也卡登陆界面，看来是代码出问题了

嗯，是的，直接试了源码，也是这样，扫码会卡住

**Comment by zlhdd108** [comment]
docker版还会卡“专项答题”，每次专项答题，都会显示“无可用提示”，然后就退出了；直接用源码运行的时候是可以正常运行的

**Comment by DoveBoy** [comment]
PC上也是这样的

**Comment by zlhdd108** [comment]
新版本已经解决
