### ISSUE TITLE
全新环境下源码运行时导入模块错误

### ISSUE THREAD

**Issue by joe136685182** [TechXueXi/TechXueXi#150]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

源码运行

### 软件/源码版本

v20220126

### 系统版本，包含位数

windows7 x64

### 浏览器、驱动版本

chrome v73.0.3683.86 + chromedriver v73.0.3683.68

### python版本

python3.8.8 x64

### docker tag版本

不使用 docker

### 推送方式

不使用或不开启推送

### 详细描述

执行 `pip install -r requirements.txt` 安装依赖后无法启动学习脚本，提示导入「itsdangerous」模块时找不到「json」方法。
`cannot import name 'json' from 'itsdangerous'   检测到你有python模块找不到，你可在搜索引擎搜索安装相关模块。`
经过对比，发现是因为「itsdangerous」在v2.1.0中去掉了「json」方法，所以降级至v2.0.1版即可解决问题。
执行 `pip install -U itsdangerous==2.0.1` 即可
修复建议：在 `requirements.txt` 中增加「itsdangerous==2.0.1」指定依赖版本即可。

**Comment by techxuexi21** [comment]
非常感谢，已更新代码
