### ISSUE TITLE
mac下运行源代码出错

### ISSUE THREAD

**Issue by zhutie-oldsuperman** [TechXueXi/TechXueXi#152]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

源码运行

### 软件/源码版本

20220126

### 系统版本，包含位数

mac os 11.6

### 浏览器、驱动版本

版本 98.0.4758.109（正式版本） mac版

### python版本

pip 21.2.4 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)

### docker tag版本

不使用

### 推送方式

不使用或不开启推送

### 详细描述

dellimac@DelliMacdeiMac SourcePackages % python ./pandalearning.py
  File "./pandalearning.py", line 11
SyntaxError: Non-ASCII character '\xe5' in file ./pandalearning.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by weiwan7** [comment]
python3

**Comment by techxuexi21** [comment]
```
python3 ./pandalearning.py
```
