### ISSUE TITLE
docker使用网页推送，访问时出现“科技强国登录平台”认证登录，请问默认的用户名和密码是什么

### ISSUE THREAD

**Issue by 19819068211** [TechXueXi/TechXueXi#159]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

techxuexi/techxuexi-amd64:dev86

### 系统版本，包含位数

ubuntu16.04

### 浏览器、驱动版本

chrome

### python版本

python3.7

### docker tag版本

dev86

### 推送方式

6 网页推送

### 详细描述

![屏幕截图(75)](https://user-images.githubusercontent.com/66981884/162602523-23567e84-a04a-4b90-9c1d-47dc3f5c5244.png)
作者大大，docker使用网页推送，访问时出现“科技强国登录平台”认证登录，请问默认的用户名和密码是什么

**Comment by techxuexi21** [comment]
@19819068211 你真的已经仔细阅读过 常见问题汇总 和 Docker运行文档 了吗？里面已经写了   https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB

**Comment by indiboy** [comment]
techxuexi
techxuexi.js.org
