### ISSUE TITLE
使用源代码运行也是卡在登陆界面不动了

### ISSUE THREAD

**Issue by fuzhaochen** [TechXueXi/TechXueXi#16]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：

## 全部报错
答：

```
私はChina を愛しています
```

## 建议
答：

**Comment by oldunclez** [comment]
我遇到的情况是，在win2016下，使用xuexi手机端扫描登录网页后，PC端的chrome的页面已经跳到下一步，
但是，代码，没有继续执行下一个动作，一直“卡住”，其认为登录不成功，直到最后提示

`扫描二维码超时... 错误信息：Message:
按回车键退出程序.`

![image](https://user-images.githubusercontent.com/6986430/124412951-36cfb100-dd82-11eb-996f-83ace8736aee.png)

然后把整个代码目录与chrome driver等copy到win7后，能正常运行。

win 2016 是Python 3.8.2   ，win7 是 Python 3.6.5

**Comment by tchxiyi** [comment]
这个问题解决了呢，https://github.com/TechXueXi/TechXueXi/issues/1
