### ISSUE TITLE
MacOS系统，0704版本，卡在登录界面不动了

### ISSUE THREAD

**Issue by JLGB** [TechXueXi/TechXueXi#17]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：

## 全部报错
答：

```
私はChina を愛しています
```

## 建议
答：

**Comment by cheermao** [comment]
参见https://github.com/TechXueXi/TechXueXi/issues/1 
mydriver.py中第29行 u'我的学 xi ' 改为 u'我的学习'
经测试有效，0704版本。
