### ISSUE TITLE
一些需要处理的问题

### ISSUE THREAD

**Issue by AnKyrk** [TechXueXi/TechXueXi#171]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

D86

### 系统版本，包含位数

docker

### 浏览器、驱动版本

chrome v99 

### python版本

python3.7

### docker tag版本

dev86

### 推送方式

6 网页推送

### 详细描述

作者大大 您好！

我详细研究了一下您的代码，发现存在几个问题:

1. webdriver标识伪装不彻底，存在封号风险！ 个人觉得您应该试着了解一下 `undetected_chromedriver` 这个包
2. 登录界面形同虚设，登录账号密码存在于明文源码中！**我自己用，运营商把我域名封了！没谁了** ，这也让我想起某家的光猫
3. 更新功能无法使用，更新困难，每一次都删了重建，不人性化对吧
4. 建议您修正一下获取二维码的方式，可以是长轮询吗对吧

以上只是个人的一点小小的建议，我python学的也不好，说的不对的地方，请见谅
另外建议您重构部分代码，有些地方属实效率有点低

**Comment by techxuexi21** [comment]
@AnKyrk 您有兴趣可以提交pr，谢谢

**Comment by AnKyrk** [comment]
@techxuexi21  感谢您的回复，我实在是没时间，公司忙死啦
