### ISSUE TITLE
docker如何更新到developing版最新？

### ISSUE THREAD

**Issue by hackenfu** [TechXueXi/TechXueXi#172]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

v20220210

### 系统版本，包含位数

不适用

### 浏览器、驱动版本

不适用

### python版本

不适用

### docker tag版本

latest

### 推送方式

5 telegram

### 详细描述

docker latest版本，初试拉取的时候应该是对应到master分支版本，也就是v20220126
后续通过telegram的/update，可以更新到dev分支的最新版本，也就是v20220210
不知道如何才能更新到developing的最新版本，也就是v20220411？

**Comment by techxuexi21** [comment]
@hackenfu 不建议更新到developing 分支，因为会推送没有开发完的代码到此分支。很久没有更新dev分支是因为开发组内无人测试并合并。
