### ISSUE TITLE
真邪乎，有的时候正常，有的时候每日答题只答四道

### ISSUE THREAD

**Issue by mayjack0312** [TechXueXi/TechXueXi#184]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

v20220126

### 系统版本，包含位数

Windows10 x64

### 浏览器、驱动版本

Chrome v102.0.5005.63 + Chromedriver v102.0.5005.61

### python版本

python3.7.12 x32

### docker tag版本

latest

### 推送方式

6 网页推送

### 详细描述

以下是第一遍的运行日志
我跑了两遍才达到45分
（之前没发现有这问题）OwO
```
xxx.xxx.xx.x - - [02/Jun/2022 00:36:19] "GET /api/list_users_status_from_memory HTTP/1.1" 200 -
xxx.xxx.xx.x - - [02/Jun/2022 00:36:19] "GET /api/list_messages HTTP/1.1" 200 -
XXX 当前学 xi 总积分：468	今日得分：44
阅读文章: 6 / 6 , 观看视频: 6 / 6 , 文章时长: 6 / 6 , 视频时长: 6 / 6 , 
每日登陆: 1 / 1 , 每日答题: 4 / 5 , 每周答题: 5 / 5 , 专项答题: 10 / 10
xxx.xxx.xx.x - - [02/Jun/2022 00:36:20] "GET /api/refresh_all_cookies HTTP/1.1" 200 -
xxx.xxx.xx.x - - [02/Jun/2022 00:36:20] "GET /api/list_users_status_from_memory HTTP/1.1" 200 -
xxx.xxx.xx.x - - [02/Jun/2022 00:36:20] "GET /api/now HTTP/1.1" 200 -
```

**Comment by EasonFP** [comment]
我也遇到了，不过差一分有时候不管了、不拿满也问题不大

**Comment by mayjack0312** [comment]
> 我也遇到了，不过差一分有时候不管了、不拿满也问题不大

hh

**Comment by ddzzhen** [comment]
因为有些题没有答案，需要手动答题

**Comment by mayjack0312** [comment]
> 因为有些题没有答案，需要手动答题

唉，难搞；最近确实又是连着两天出现这怪事了
有的题答案不对，也有的题根本不知道答案
（基本都得跑两次才能满分）(*^▽^*)

**Comment by GnaixEuy** [comment]
视频题无法自动补充，所以只有4分

**Comment by GnaixEuy** [comment]
可以关issue了

**Comment by aili5320** [comment]
/api/list_users_status_from_memory 这个接口调不通咋处理
