### ISSUE TITLE
微信接口配置失败 求助！

### ISSUE THREAD

**Issue by minealex** [TechXueXi/TechXueXi#188]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

v20211221

### 系统版本，包含位数

 windows10 x64

### 浏览器、驱动版本

chrome 102.0.5005.63

### python版本

python 3.9.2

### docker tag版本

latest

### 推送方式

2 微信

### 详细描述
已改用别的方法了

**Comment by beichen123-hub** [comment]
端口8088 必须保证内部容器8088打开

**Comment by minealex** [comment]
> 端口8088 必须保证内部容器8088打开

端口是打开的，请看下图

![端口](https://user-images.githubusercontent.com/24503832/174612699-396ae1cd-1ca3-44e2-9e5d-ec6e2533ecda.jpg)

**Comment by beichen123-hub** [comment]
你这个是配置你需要在你的服务器打开端口 比如你使用的是ikuai你就需要在ikuai里面打开内部8088映射到公网端口

**Comment by minealex** [comment]
> 

我是windows11 直接用docker-compose.yml，服务器就是我的电脑吗？怎么打开8088端口？我我查看任务管理器中8088端口确实是docker在用，现在我感觉可能是微信访问不到我电脑的8088端口

**Comment by minealex** [comment]
> 你这个是配置你需要在你的服务器打开端口 比如你使用的是ikuai你就需要在ikuai里面打开内部8088映射到公网端口

我是windows11 直接用docker-compose.yml，服务器就是我的电脑吗？怎么打开8088端口？我我查看任务管理器中8088端口确实是docker在用，现在我感觉可能是微信访问不到我电脑的8088端口

**Comment by beichen123-hub** [comment]
首先你得有固定ip 然后开放端口

**Comment by minealex** [comment]
> 首先你得有固定ip 然后开放端口

我是用花生壳映射到我电脑的8088端口，微信配置中填了花生壳的映射域名，但微信依然访问不到

**Comment by mayjack0312** [comment]
@minealex 能ping通再考虑是不是端口的问题

**Comment by minealex** [comment]
> @minealex 能ping通再考虑是不是端口的问题

花生壳域名能ping通，但微信就是配置失败，很奇怪

**Comment by beichen123-hub** [comment]
你需要看你电脑内网8088开没有，这个内网8088是需要你的docker容器里能跟公网传来的数据进行交互

**Comment by minealex** [comment]
> 
这样算是开了吗？

![174612699-396ae1cd-1ca3-44e2-9e5d-ec6e2533ecda](https://user-images.githubusercontent.com/24503832/174993965-cf99da27-8d01-470c-bd7a-587f784c797f.jpg)
这是docker-compose.yml的配置

![端口打开状态](https://user-images.githubusercontent.com/24503832/174994054-a7d6b8d5-f2ec-480d-a424-755db607d2d9.jpg)
这是端口状态

![PID](https://user-images.githubusercontent.com/24503832/174994086-c0d597e2-7fa4-4c54-8d2b-944a9daf3d0a.jpg)
这是PID状态

**Comment by minealex** [comment]
> 你需要看你电脑内网8088开没有，这个内网8088是需要你的docker容器里能跟公网传来的数据进行交互

这样算是开了吗？

![174612699-396ae1cd-1ca3-44e2-9e5d-ec6e2533ecda](https://user-images.githubusercontent.com/24503832/174993965-cf99da27-8d01-470c-bd7a-587f784c797f.jpg)
这是docker-compose.yml的配置

![端口打开状态](https://user-images.githubusercontent.com/24503832/174994054-a7d6b8d5-f2ec-480d-a424-755db607d2d9.jpg)
这是端口状态

![PID](https://user-images.githubusercontent.com/24503832/174994086-c0d597e2-7fa4-4c54-8d2b-944a9daf3d0a.jpg)
这是PID状态

**Comment by beichen123-hub** [comment]
开了，你有这时间你买个服务器吧或者你把他放到路由器里吧

**Comment by zlhdd108** [comment]
![image](https://user-images.githubusercontent.com/16465666/175043716-0b634ca8-1b1f-458e-bd12-bf6af1efff47.png)

telnet端口都不通，开个鬼；域名都没有解析，你想怎么访问？

**Comment by zlhdd108** [comment]
![image](https://user-images.githubusercontent.com/16465666/175049906-09f660ac-60bd-4c03-a527-690bd6aa2bda.png)
按照这个看，域名用https访问的时候就直接指向了内网的8088；443就是https的协议端口

**Comment by minealex** [comment]
已改用别的方法了
