### ISSUE TITLE
An exception occurred on pdlearn.answer_question.answer_question:'domain'

### ISSUE THREAD

**Issue by cikichen** [TechXueXi/TechXueXi#192]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

源码运行

### 软件/源码版本

v20220411

### 系统版本，包含位数

mac

### 浏览器、驱动版本

103.0.5060.114 + 103.0.5060.53

### python版本

Python 3.9.13

### docker tag版本

不适用docker

### 推送方式

不使用或不开启推送

### 详细描述

开启： 获取更新信息...
[*] 正在联网获取更新信息...(更新显示不会打断之前输入等操作)
开启： 151138921908开始学xi
是否无头模式：False None
当前选择模式：3
============================================================
欢迎使用 TechXueXi
[*] TechXueXi最新下载地址为 https://github.com/TechXueXi/TechXueXi
[*] 程序版本为：v20220411
[*] 最新稳定版为：v20220126

阅读文章: 0 / 6 , 观看视频: 0 / 6 , 文章时长: 0 / 6 , 视频时长: 0 / 6 ,
每日登陆: 1 / 1 , 每日答题: 0 / 5 , 每周答题: 0 / 5 , 专项答题: 0 / 10
 登录正常，开始学习...

开启： 文章学 xi
开启： 视频学 xi
文章学 xi 检测到异常：'domain'
视频学 xi 检测到异常：'domain'
开始每日答题……
请保持窗口最大化
请保持窗口最大化
请保持窗口最大化

An exception occurred on pdlearn.answer_question.answer_question:'domain'
开始每周答题……
请保持窗口最大化
请保持窗口最大化
请保持窗口最大化

An exception occurred on pdlearn.answer_question.answer_question:'domain'
开始专项答题……
请保持窗口最大化
请保持窗口最大化
请保持窗口最大化

An exception occurred on pdlearn.answer_question.answer_question:'domain'

**Comment by tanbinzone** [comment]
同样的错误，macos

**Comment by Silentely** [comment]
同样docker报错

开启： 文章学 xi 
开启： 视频学 xi 
视频学 xi 检测到异常：'domain'
文章学 xi 检测到异常：'domain'
开始每日答题……
请保持窗口最大化
请保持窗口最大化
请保持窗口最大化

An exception occurred on pdlearn.answer_question.answer_question:'domain'
开始每周答题……

**Comment by zengerlin** [comment]
同样docker报错

开启： 文章学 xi
开启： 视频学 xi
视频学 xi 检测到异常：'domain'
文章学 xi 检测到异常：'domain'
开始每日答题……
请保持窗口最大化
请保持窗口最大化
请保持窗口最大化

An exception occurred on pdlearn.answer_question.answer_question:'domain'
开始每周答题……
