### ISSUE TITLE
做专题时出错，不能完成。

### ISSUE THREAD

**Issue by chenyuyou** [TechXueXi/TechXueXi#210]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

Docker运行

### 软件/源码版本

v20220711

### 系统版本，包含位数

docker

### 浏览器、驱动版本

chromedriver_linux64_92.0.4515.107.zip

### python版本

Python 3.7.13

### docker tag版本

dev89

### 推送方式

5 telegram

### 详细描述

做专题时，会出现以下代码

An exception occurred on pdlearn.answer_question.answer_question:Message: stale element reference: element is not attached to the page document (Session info: headless chrome=92.0.4515.159)

**Comment by kt7a** [comment]
我也有类似的问题，出错信息如下：

一点小问题： Message: 
An exception occurred on pdlearn.answer_question.answer_question:Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app"]/div/div[2]/div/div[3]/div[2]/div[7]/div[2]/div[2]/div"}
  (Session info: headless chrome=92.0.4515.159)
