### ISSUE TITLE
请修改这里的名称

### ISSUE THREAD

**Issue by superyy91** [TechXueXi/TechXueXi#211]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

一般运行（现在不提供支持）

### 软件/源码版本

v20220126

### 系统版本，包含位数

win10 x64

### 浏览器、驱动版本

chrome 版本 5.1.8.16 32 位

### python版本

无

### docker tag版本

不使用

### 推送方式

不使用或不开启推送

### 详细描述

Cloning into 'TechXuexi-master-clone'...
fatal: unable to access 'https://github.com.cnpmjs.org/TechXueXi/TechXueXi.git/': Could not resolve host: github.com.cnpmjs.org
[*] 出现错误！请反馈此问题：git_clone_出错  小白求助！

**Comment by sunshanpeng** [comment]
网址搞错了，用`https://github.com/TechXueXi/TechXueXi.git`

**Comment by FlorenceZh** [comment]
你使用的使用镜像不支持git clone。
若有需求请使用[fastgit](fastgit.xyz)这样支持git clone操作的镜像。
