### ISSUE TITLE
求大神解决，windows下已经不能运行了，扫码登入会显示  扫描二维码超时... 错误信息：'1878142'

### ISSUE THREAD

**Issue by Dark21Knight** [TechXueXi/TechXueXi#218]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

源码运行

### 软件/源码版本

v20220126

### 系统版本，包含位数

windows10 x64

### 浏览器、驱动版本

没更新还是chrome v73.0 + chromedriver v 73.0

### python版本

没更新还是python3.6.8 x32

### docker tag版本

不使用

### 推送方式

不使用或不开启推送

### 详细描述

1.windows下已经不能运行了，扫码登入会显示  扫描二维码超时... 错误信息：'1878142'，
2.如能解决希望顺便解决下滑块

**Comment by BaiHLiu** [comment]
同样的问题，Linux docker-amd64最新版本提示：
`扫描二维码超时... 错误信息：'151114554767'`

**Comment by BaiHLiu** [comment]
> 同样的问题，Linux docker-amd64最新版本提示： `扫描二维码超时... 错误信息：'151114554767'`

补充信息：在同一台主机使用同一IP，可在网页端正常登陆；积分2w+。

**Comment by chinaworker** [comment]
同问：
在windows 7下扫描二维码提示错误：
get_score 获取失败:'NoneType' object is not subscriptable

 File "E:\学习强国\SourcePackages\pdlearn\score.py", line 26, in show_score
   "\t" + "今日得分：" + str(scores["today"]))
typeError: 'int' object is not subscriptable

**Comment by weiwan7** [comment]
获取总分数的接口地址变了 
修改/xuexi/pdlearn/score.py文件 
头部加入 
import time 
import datetime 
 
 
get_score函数中 
total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar, 
 
修改为: 
t = time.time() 
total_json = requests.get("https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d"%(int(round(t * 1000))), cookies=jar,

**Comment by lueasy559** [comment]
> 
解决了，感谢大佬

**Comment by chinaworker** [comment]
谢谢，我的问题解决了。

**Comment by MaQuchen** [comment]
谢谢，解决了，万分感谢

**Comment by BaiHLiu** [comment]
谢谢，解决了！

**Comment by liu-youyu** [comment]
> 获取总分数的接口地址变了 修改/xuexi/pdlearn/score.py文件 头部加入 import time import datetime
> 
> get_score函数中 total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar,
> 
> 修改为: t = time.time() total_json = requests.get("[https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d"%(int(round(t](https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d%22%(int(round(t) * 1000))), cookies=jar,

问题解决了，特来感谢！

**Comment by matthkewk** [comment]
谢谢，解决了！

**Comment by gzncpcc** [comment]
> 获取总分数的接口地址变了 修改/xuexi/pdlearn/score.py文件 头部加入 import time import datetime
> 
> get_score函数中 total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar,
> 
> 修改为: t = time.time() total_json = requests.get("[https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d"%(int(round(t](https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d%22%(int(round(t) * 1000))), cookies=jar,

解决了，感谢大佬

**Comment by Dark21Knight** [comment]
> total_json = requests.get("[https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d"%(int(round(t](https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d%22%(int(round(t) * 1000))), cookies=jar,

谢谢大神，终于解决了

**Comment by zeroxia** [comment]
我改了也不行，是因为网络问题吗？

```
DevTools listening on ws://127.0.0.1:64282/devtools/browser/c6668183-6e83-46cc-8e21-69bf256e2b6a
正在打开二维码登陆界面,请稍后
扫描二维码超时... 错误信息：HTTPSConnectionPool(host='pc-proxy-api.xuexi.cn', port=443): Max retries exceeded with url: /delegate/score/get?_t=1677551885140 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
按回车键退出程序.
```

**Comment by sparklerl** [comment]
> 获取总分数的接口地址变了 修改/xuexi/pdlearn/score.py文件 头部加入 import time import datetime
> 
> get_score函数中 total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar,
> 
> 修改为: t = time.time() total_json = requests.get("[https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d"%(int(round(t](https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d%22%(int(round(t) * 1000))), cookies=jar,
谢谢大佬，成功解决

**Comment by sparklerl** [comment]
> 获取总分数的接口地址变了 修改/xuexi/pdlearn/score.py文件 头部加入 import time import datetime
> 
> get_score函数中 total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar,
> 
> 修改为: t = time.time() total_json = requests.get("[https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d"%(int(round(t](https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d%22%(int(round(t) * 1000))), cookies=jar,

谢谢大佬，成功解决

**Comment by Dark21Knight** [comment]
> 我改了也不行，是因为网络问题吗？
> 
> ```
> DevTools listening on ws://127.0.0.1:64282/devtools/browser/c6668183-6e83-46cc-8e21-69bf256e2b6a
> 正在打开二维码登陆界面,请稍后
> 扫描二维码超时... 错误信息：HTTPSConnectionPool(host='pc-proxy-api.xuexi.cn', port=443): Max retries exceeded with url: /delegate/score/get?_t=1677551885140 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
> 按回车键退出程序.
> ```

你看看是不是漏了哪个没改

**Comment by zsc990338** [comment]
谢大神救命之恩，问题解决了，天天要和这个破平台斗智斗勇，真真心累阿！

**Comment by domeniczz** [comment]
> 我改了也不行，是因为网络问题吗？
> 
> ```
> DevTools listening on ws://127.0.0.1:64282/devtools/browser/c6668183-6e83-46cc-8e21-69bf256e2b6a
> 正在打开二维码登陆界面,请稍后
> 扫描二维码超时... 错误信息：HTTPSConnectionPool(host='pc-proxy-api.xuexi.cn', port=443): Max retries exceeded with url: /delegate/score/get?_t=1677551885140 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
> 按回车键退出程序.
> ```

你是不是忘记关代理软件了

**Comment by zeroxia** [comment]
> 

可能是代理或者内部网络问题。

**Comment by Jacksx20** [comment]
> > 我改了也不行，是因为网络问题吗？
> > ```
> > DevTools listening on ws://127.0.0.1:64282/devtools/browser/c6668183-6e83-46cc-8e21-69bf256e2b6a
> > 正在打开二维码登陆界面,请稍后
> > 扫描二维码超时... 错误信息：HTTPSConnectionPool(host='pc-proxy-api.xuexi.cn', port=443): Max retries exceeded with url: /delegate/score/get?_t=1677551885140 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
> > 按回车键退出程序.
> > ```
> 
> 你是不是忘记关代理软件了

把接口 "https://pc-api.xuexi.cn/open/api/score/get" 换成 "https://pc-proxy-api.xuexi.cn/delegate/score/get" 这个解决问题了

**Comment by Jacksx20** [comment]
> 我改了也不行，是因为网络问题吗？
> 
> ```
> DevTools listening on ws://127.0.0.1:64282/devtools/browser/c6668183-6e83-46cc-8e21-69bf256e2b6a
> 正在打开二维码登陆界面,请稍后
> 扫描二维码超时... 错误信息：HTTPSConnectionPool(host='pc-proxy-api.xuexi.cn', port=443): Max retries exceeded with url: /delegate/score/get?_t=1677551885140 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
> 按回车键退出程序.
> ```

网络问题 查看一下代理还有网络连接
