### ISSUE TITLE
20210705版答题时间比20210605版增加十多分钟

### ISSUE THREAD

**Issue by 3xxx** [TechXueXi/TechXueXi#23]
**系统版本，包含位数**：20210705

**python版本**：20210705

**软件/源码版本**：20210705

**浏览器、驱动版本**：

-----

## 详细描述
答：20210705版本答题时间比20210605答题时间多出十多分钟。主要是文章、视频学习方面。老版本十多分钟搞定，新版本需要20多分钟。

## 建议
答：对比一下源码，看看是否可以优化。

**Comment by gush4** [comment]
视频学习模块需要重写
