### ISSUE TITLE
扫码后显示cookie过期，请重新登录

### ISSUE THREAD

**Issue by Jacksx20** [TechXueXi/TechXueXi#230]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

源码运行

### 软件/源码版本

v20220711

### 系统版本，包含位数

win11

### 浏览器、驱动版本

chrome v98.0.4758.102

### python版本

python3.7.5

### docker tag版本

不使用

### 推送方式

不使用或不开启推送

### 详细描述

扫码后显示cookie过期，请重新登录
扫描二维码超时... 错误信息：No active exception to reraise
![image](https://user-images.githubusercontent.com/66831345/224467726-5f64bae1-3589-48a2-b5c7-84d787eedef0.png)

**Comment by dddog999** [comment]
跑路了吧

**Comment by Windstarry** [comment]
把SourcePackages/pdlearn/score.py第66到74行注释掉，
total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar,
headers={'Cache-Control': 'no-cache'}).content.decode("utf8")
if not json.loads(total_json)["data"]:
globalvar.pushprint("cookie过期，请重新登录", chat_id)
if chat_id:
remove_cookie(chat_id)
raise
total = int(json.loads(total_json)["data"]["score"])
修改为 total = 10000
应该是获取积分的接口无效了。

**Comment by liheji** [comment]
> 把SourcePackages/pdlearn/score.py第66到74行注释掉， total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar, headers={'Cache-Control': 'no-cache'}).content.decode("utf8") if not json.loads(total_json)["data"]: globalvar.pushprint("cookie过期，请重新登录", chat_id) if chat_id: remove_cookie(chat_id) raise total = int(json.loads(total_json)["data"]["score"]) 修改为 total = 10000 应该是获取积分的接口无效了。

把接口 "https://pc-api.xuexi.cn/open/api/score/get" 
换成 "https://pc-proxy-api.xuexi.cn/delegate/score/get" 这个就行

**Comment by Jacksx20** [comment]
> > 把SourcePackages/pdlearn/score.py第66到74行注释掉， total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar, headers={'Cache-Control': 'no-cache'}).content.decode("utf8") if not json.loads(total_json)["data"]: globalvar.pushprint("cookie过期，请重新登录", chat_id) if chat_id: remove_cookie(chat_id) raise total = int(json.loads(total_json)["data"]["score"]) 修改为 total = 10000 应该是获取积分的接口无效了。
> 
> 把接口 "https://pc-api.xuexi.cn/open/api/score/get" 换成 "https://pc-proxy-api.xuexi.cn/delegate/score/get" 这个就行

好的我试试

**Comment by Jacksx20** [comment]
把接口 "https://pc-api.xuexi.cn/open/api/score/get" 换成 "https://pc-proxy-api.xuexi.cn/delegate/score/get" 这个解决问题了
