### ISSUE TITLE
如何跳过每周答题与专项答题

### ISSUE THREAD

**Issue by hanyujie177** [TechXueXi/TechXueXi#237]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

一般运行（现在不提供支持）

### 软件/源码版本

v20220126

### 系统版本，包含位数

 windows7 x64

### 浏览器、驱动版本

chrome 111.0.5563.111

### python版本

无

### docker tag版本

无

### 推送方式

不使用或不开启推送

### 详细描述

如何跳过每周答题与专项答题，只需要文章+视频+每日+登录即可，求助大佬

**Comment by hanyujie177** [comment]
因为目前官方关闭了每周答题入口，但程序依然检测，会导致程序卡顿一段时间报出exception再继续，请问有什么办法跳过每周答题检测吗

**Comment by liheji** [comment]
修改 pandalearning.py 文件，如下weekly() 函数代表每周答题，zhuanxiang()函数代表专项答题，不要注释掉就行 
![image](https://user-images.githubusercontent.com/56494145/228500012-94853542-3e27-4499-83a0-496ce9fb31b8.png)

**Comment by hanyujie177** [comment]
> 

感谢 采纳后已解决

**Comment by hanyujie177** [comment]
> 修改 pandalearning.py 文件，如下weekly() 函数代表每周答题，zhuanxiang()函数代表专项答题，不要注释掉就行 ![image](https://user-images.githubusercontent.com/56494145/228500012-94853542-3e27-4499-83a0-496ce9fb31b8.png)

解决方案
