### ISSUE TITLE
扫描二维码超时... 错误信息：Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by a458895535** [TechXueXi/TechXueXi#239]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

源码运行

### 软件/源码版本

v20220126

### 系统版本，包含位数

windows10 x64

### 浏览器、驱动版本

chrome 111.0.5563.147 

### python版本

python 3.7.6

### docker tag版本

无

### 推送方式

不使用或不开启推送

### 详细描述

![image](https://user-images.githubusercontent.com/28849906/230033375-fa688fc4-d3fb-4b82-ba97-5cab125db25f.png)
如上，扫码无法登录

**Comment by ngrict** [comment]
同样的错误，在根据 [#228](https://github.com/TechXueXi/TechXueXi/issues/228) 修改并添加了 total = 99999之后出现。

**Comment by a458895535** [comment]
> 同样的错误，在根据 [#228](https://github.com/TechXueXi/TechXueXi/issues/228) 修改并添加了 total = 99999之后出现。

是的，在修改 total = 10000之后出现了这个问题

**Comment by reedlxm** [comment]
我也是这个情况。现在已经解决了。
是按照228修改后，还需要修改234的那条URL
2个地方都修改了就不会报这个错误了

**Comment by fanpink** [comment]
## 原因：
docker版项目已经很久没更新了，xuexiqiangguo网页版官方已经更换了api地址。解决办法更改一个文件的两个地方。
原来的api
```
# 总积分
# https://pc-api.xuexi.cn/open/api/score/get?_t=1608769882241
# 今日积分
# https://pc-api.xuexi.cn/open/api/score/today/query
```
现在的api
```
# 总积分
# https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=1682489708280
# 今日积分
# https://pc-proxy-api.xuexi.cn/delegate/score/today/query
```
## 需要修改文件：
pdlearn目录下score.py文件

### 说明：
很多大神都说了很清楚了，考虑到可能有部分更我一样的半吊子弄不好，我尽量说细一点（我这个半吊子也是折腾好半天才解决）
# 步骤：
#  一、先进入容器终端：
windows下docker很简单就不说了，主要说一下linux下：
## 1查看运行容器
`# docker ps --format "{{.Names}}"`
### 显示
`techxuexi-web`
## 2.进入Docker容器
使用Docker exec命令进入到Docker容器中，例如：

`# docker exec -it techxuexi-web /bin/bash`
## 3.进入容器内终端，安装vim，（根据自己使用习惯安装合适自己的工具）
`apt install vim`
## 4进入pdlearn目录
`cd pdlearn`
## 5编辑score.py（此部分放在最后单独说明，请跳到最后）
`vim score.py`
# 二、修改score.py
## 1.第一步
### 第10行添加内容

### 10行添加
```
import time
import datetime
```
## 2.第二步 
### 需要修改内容

原66行前（现68行）

`
total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar,
`

### 修改为
原66行前（现68行）添加
```
t = time.time()
```
###修改前

```
total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar,
```

### 修改为

```
total_json = requests.get("https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d"%(int(round(t * 1000))), cookies=jar,
```
## 3.第三步 
### 需要修改内容
```
score_json = requests.get("https://pc-proxy-api.xuexi.cn/api/score/days/listScoreProgress?sence=score&deviceType=2", cookies=jar,
```
### 修改为
```
score_json = requests.get("https://pc-proxy-api.xuexi.cn/delegate/score/days/listScoreProgress?sence=score&deviceType=2", cookies=jar,
```

# 三、退出重启


### 保存修改后退出
`exit`
### 停止运行中的 Docker 容器：
`$sudo docker ps -a`
### 显示（示例）
```
CONTAINER ID   IMAGE                       COMMAND                  CREATED       STATUS          PORTS                                   NAMES
f860a0194aad   techxuexi/techxuexi-amd64   "/bin/bash ./start.sh"   3 hours ago   Up 42 minutes   0.0.0.0:9980->80/tcp, :::9980->80/tcp   techxuexi-web
```
### 停止docker （换成自己查到的容器id）
`$sudo docker stop f860a0194aad #换成自己的容器id`

其中 <CONTAINER_NAME/CONTAINER_ID> 是要重启的 Docker 容器的名称或者ID。
### 启动 Docker 容器：
`$sudo docker start f860a0194aad`

**Comment by w11nd** [comment]
> fanpink

需要再打包成新的镜像吧？

**Comment by fanpink** [comment]
> 

不需要直接修改就行，重启容器生效

**Comment by w11nd** [comment]
> > 
> 
> 不需要直接修改就行，重启容器生效

好的，谢谢

**Comment by w11nd** [comment]
score_json = requests.get("https://pc-proxy-api.xuexi.cn/delegate/score/days/listScoreProgress?sence=score&deviceType=2", cookies=jar,
这个地方也需要更改api

**Comment by leic4u** [comment]
> ## 原因：
> docker版项目已经很久没更新了，xuexiqiangguo网页版官方已经更换了api地址。解决办法更改一个文件的两个地方。 原来的api
> 
> ```
> # 总积分
> # https://pc-api.xuexi.cn/open/api/score/get?_t=1608769882241
> # 今日积分
> # https://pc-api.xuexi.cn/open/api/score/today/query
> ```
> 
> 现在的api
> 
> ```
> # 总积分
> # https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=1682489708280
> # 今日积分
> # https://pc-proxy-api.xuexi.cn/delegate/score/today/query
> ```
> 
> ## 需要修改文件：
> pdlearn目录下score.py文件
> 
> ### 说明：
> 很多大神都说了很清楚了，考虑到可能有部分更我一样的半吊子弄不好，我尽量说细一点（我这个半吊子也是折腾好半天才解决）
> 
> # 步骤：
> # 一、先进入容器终端：
> windows下docker很简单就不说了，主要说一下linux下：
> 
> ## 1查看运行容器
> `# docker ps --format "{{.Names}}"`
> 
> ### 显示
> `techxuexi-web`
> 
> ## 2.进入Docker容器
> 使用Docker exec命令进入到Docker容器中，例如：
> 
> `# docker exec -it techxuexi-web /bin/bash`
> 
> ## 3.进入容器内终端，安装vim，（根据自己使用习惯安装合适自己的工具）
> `apt install vim`
> 
> ## 4进入pdlearn目录
> `cd pdlearn`
> 
> ## 5编辑score.py（此部分放在最后单独说明，请跳到最后）
> `vim score.py`
> 
> # 二、修改score.py
> ## 1.第一步
> ### 第10行添加内容
> ### 10行添加
> ```
> import time
> import datetime
> ```
> 
> ## 2.第二步
> ### 需要修改内容
> 原66行前（现68行）
> 
> `total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar,`
> 
> ### 修改为
> 原66行前（现68行）添加
> 
> ```
> t = time.time()
> ```
> 
> ###修改前
> 
> ```
> total_json = requests.get("https://pc-api.xuexi.cn/open/api/score/get", cookies=jar,
> ```
> 
> ### 修改为
> ```
> total_json = requests.get("https://pc-proxy-api.xuexi.cn/delegate/score/get?_t=%d"%(int(round(t * 1000))), cookies=jar,
> ```
> 
> ## 3.第三步
> ### 需要修改内容
> ```
> score_json = requests.get("https://pc-proxy-api.xuexi.cn/api/score/days/listScoreProgress?sence=score&deviceType=2", cookies=jar,
> ```
> 
> ### 修改为
> ```
> score_json = requests.get("https://pc-proxy-api.xuexi.cn/delegate/score/days/listScoreProgress?sence=score&deviceType=2", cookies=jar,
> ```
> 
> # 三、退出重启
> ### 保存修改后退出
> `exit`
> 
> ### 停止运行中的 Docker 容器：
> `$sudo docker ps -a`
> 
> ### 显示（示例）
> ```
> CONTAINER ID   IMAGE                       COMMAND                  CREATED       STATUS          PORTS                                   NAMES
> f860a0194aad   techxuexi/techxuexi-amd64   "/bin/bash ./start.sh"   3 hours ago   Up 42 minutes   0.0.0.0:9980->80/tcp, :::9980->80/tcp   techxuexi-web
> ```
> 
> ### 停止docker （换成自己查到的容器id）
> `$sudo docker stop f860a0194aad #换成自己的容器id`
> 
> 其中 <CONTAINER_NAME/CONTAINER_ID> 是要重启的 Docker 容器的名称或者ID。
> 
> ### 启动 Docker 容器：
> `$sudo docker start f860a0194aad`

亲测有效，感谢如此详细的指导。

**Comment by birdxs** [comment]
> Referen

感谢指导，可以参考、对照这个文件修改
https://github.com/TechXueXi/TechXueXi/blob/developing/SourcePackages/pdlearn/score.py
