### ISSUE TITLE
系统检测，您的账号存在不规范xuexi行为

### ISSUE THREAD

**Issue by CoderHaay** [TechXueXi/TechXueXi#242]
### 清单

- [X] 我已经仔细阅读过 README 使用方法-更新方法-下载方式 ， DOCKER 这些说明，可以通过菜单切换 https://github.com/TechXueXi/TechXueXi/wiki
- [X] 我已经仔细阅读过 常见问题汇总 https://github.com/TechXueXi/TechXueXi/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E6%B1%87%E6%80%BB
- [X] 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/TechXueXi/issues?q=is%3Aissue
- [X] 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
- [X] 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14

### 运行方式

源码运行

### 软件/源码版本

v20020126

### 系统版本，包含位数

windows 10 x64

### 浏览器、驱动版本

chrome  111.0.5563.65

### python版本

python3.10

### docker tag版本

不使用

### 推送方式

不使用或不开启推送

### 详细描述

经系统检测，您的账号存在不规范学习行为，若再次发现，将被执行相应处理，请规范学习行为。
能正常使用，但是系统提示了这个，不敢继续用了，怎么办？

**Comment by BBSMLtd** [comment]
一样，别用了，第三次就封禁若干天

**Comment by Hohenheim-wick** [comment]
所以，这是啥原因嘞，是操作逻辑被侦测了么

**Comment by wdb1130** [comment]
被封禁了好，就可以摆烂了

**Comment by Breach-hujie** [comment]
被封禁的那位同仁，能发个被封禁的截图吗，让我死死心。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TechXueXi/TechXueXi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 上午10:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [TechXueXi/TechXueXi] 系统检测，您的账号存在不规范xuexi行为 (Issue #242)





 
被封禁了好，就可以摆烂了

**Comment by wdb1130** [comment]
最近提示了几次，存在异常现象，还没被封






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TechXueXi/TechXueXi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TechXueXi/TechXueXi] 系统检测，您的账号存在不规范xuexi行为 (Issue #242)





 被封禁的那位同仁，能发个被封禁的截图吗，让我死死心。 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "TechXueXi/TechXueXi"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年4月23日(星期天) 上午10:39 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [TechXueXi/TechXueXi] 系统检测，您的账号存在不规范xuexi行为 (Issue #242) 
 
 
 
 
 
   
 被封禁了好，就可以摆烂了

**Comment by abc13542128861** [comment]
我是没有任何提示，直接无法登陆了

**Comment by Hohenheim-wick** [comment]
(*^▽^*) 我脚本都先卸载了，试错成本太高，等稳定稳定的吧

**Comment by wdb1130** [comment]
这玩意儿不都是部分媚上欺下的领导定的硬性要求吗？不能看了，正好有理由了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TechXueXi/TechXueXi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 上午9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TechXueXi/TechXueXi] 系统检测，您的账号存在不规范xuexi行为 (Issue #242)





 
(^▽^) 我脚本都先卸载了，试错成本太高，等稳定稳定的吧

**Comment by CoderHaay** [comment]
无解
