### ISSUE TITLE
扫描二维码界面自动关闭，显示超时

### ISSUE THREAD

**Issue by a843161264** [TechXueXi/TechXueXi#25]
**系统版本，包含位数**：windows11 64bit

**python版本**：3.9

**软件/源码版本**：20210712

**浏览器、驱动版本**：73.0.3683.86、73.0.3683.68

-----

## 详细描述
答：扫码界面自动关闭，并报错超时

## 全部报错
答：

```
正在打开二维码登陆界面,请稍后
未检测到SendLoginQRcode配置，请手动扫描二维码登陆...
扫描二维码超时... 错误信息：'bool' object is not callable
按回车键退出程序.
```

## 建议
答：无无无

**Comment by gush4** [comment]
已修复
