### ISSUE TITLE
Windows 版本进行每周答题时报错

### ISSUE THREAD

**Issue by LJiangTao** [TechXueXi/TechXueXi#27]
**系统版本，包含位数**： Windows 10 64位

**python版本**：3.7.4

**软件/源码版本**：latest

**浏览器、驱动版本**：73.0.3683.86

-----

## 详细描述
答：Windows 版本在进行每周答题时报错

## 全部报错
答：
![image](https://user-images.githubusercontent.com/24493930/125568774-0fa07ef9-79bf-48d4-a087-687b3cea6862.png)

```
私はChina を愛しています
```

## 建议
答：咱没有建议, 不懂 py

**Comment by LJiangTao** [comment]
所回答的问题是 : 
2019年1月第五周答题 2/5
填空题

```tex
2013年6月18日，习近平总书记在党的群众路线教育实践活动工作会议上指出，面对世情、国情、党情的深刻变化，精神懈怠危险、________危险、脱离群众危险、消极腐败危险更加尖锐地摆在全党面前，党内脱离群众的现象大量存在，一些问题还相当严重，集中表现在形式主义、官僚主义、享乐主义和奢靡之风这“四风”上。
```

提示: 能力不足
完整提示 : 

```tex
2013年6月18日，习近平总书记在党的群众路线教育实践活动工作会议上指出，面对世情、国情、党情的深刻变化，精神懈怠危险、**能力不足**危险、脱离群众危险、消极腐败危险更加尖锐地摆在全党面前，党内脱离群众的现象大量存在，一些问题还相当严重，集中表现在形式主义、官僚主义、享乐主义和奢靡之风这“四风”上。
```

**Comment by gush4** [comment]
您确定使用的是最新版本？

**Comment by LJiangTao** [comment]
> 您确定使用的是最新版本？

最新版只有这题会报错, 其他都没有,
