### ISSUE TITLE
扫描二维码界面自动关闭，显示超时

### ISSUE THREAD

**Issue by zhangxiaoshang** [TechXueXi/TechXueXi#29]
已修复

_Originally posted by @gush4 in https://github.com/TechXueXi/TechXueXi/issues/25#issuecomment-879187616_

这个问题还在啊

我是使用源码，基于节点：
commit 3998ab7c59d448f0e309c4cc570ea88ab592f619 (HEAD -> dev, origin/dev, origin/HEAD)
Author: 恩格斯 <admin@xuexi.cn>
Date:   Mon Aug 2 17:11:21 2021 +0800

    无答案题视频题跳过，支持发二维码信息到企业微信

操作系统：
macOS Catalina 版本：10.15.7(19H1030)

chromedriver 版本：
ChromeDriver 92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634})

**Comment by zhangxiaoshang** [comment]
![image](https://user-images.githubusercontent.com/19658966/128122671-7c2fa19d-9a10-4955-8448-230316cb27ac.png)

这几行注释掉就可以跑了

**Comment by gush4** [comment]
把微信模块注释。已修复并更新
#from pdlearn.qywx import WeChat

**Comment by cyxxs** [comment]
多选题
2020年全国工业APP和信息消费大赛赛事聚焦（）和（）两个方向。
A. 工业APP
B. 信息消费

有可点击的【查看提示】按钮
获取提示： ['工业APP', '信息消费']
获取选项： ['A. 工业APP', 'B. 信息消费']
含  AB 不含 []
根据提示 AB

**Comment by cyxxs** [comment]
多选题
根据《工业互联网APP培育工程实施方案（2018-2020年）》，工业互联网APP是基于（），承载（），满足（）的工业应用软件，是工业技术软件化的重要成果。
A. 工业互联网
B. 工业知识和经验
C. 特定需求

有可点击的【查看提示】按钮
获取提示： ['工业互联网', '工业知识和经验', '特定需求']
获取选项： ['A. 工业互联网', 'B. 工业知识和经验', 'C. 特定需求']
含  ABC 不含 []
根据提示 ABC

**Comment by lifansama** [comment]
填空题
电影《雷锋》里有这样一段情节，星期天，雷锋在去卫生连看病的途中经过了一处，听到广播 中说砖供应不上了，他二话不说，借了辆小车，投入到热火朝天的劳动中。
有可点击的【查看提示】按钮
获取提示： []
本题没有提示
暂时略过已达到 5 次，【 建议您将此题目的题干、提示、选项信息提交到github问题收集issue：https://github.com/TechXueXi/TechXueXi/issues/29 】

**Comment by dsfgdfg34dfgdfsgdfsgdf34534sdfgdsfgdsfg** [comment]
填空题
为助推破解新型农业经营主体“融资难、融资贵”难题，农业农村部组织开展新型农业经营主体__________直通车活动。活动开展时间为2021年5月15日-12月31日。
多选题
没有可点击的【查看提示】按钮
本题没有提示
暂时略过已达到 5 次

**Comment by BrianLeeGH** [comment]
电影《童年周恩来》中，教书先生给周恩来起的字叫翔宇，意为：“翔者飞也，宇者宇宙，翔宇即，四荒八极无所不达也”。
有可点击的【查看提示】按钮
获取提示： []
本题没有提示
没有找到提示，暂时略过

**Comment by Freed-Wu** [comment]
电影《建军大业》中，毛泽东为军队购买枪支弹药，军火商洪门老八不要粤票（1911年粤省政府发行的“中华民国粤省军政府通用银票”），只要银元，毛泽东在银元不足的情况下，附上了自己的，最终明白了枪支用途的老八以枪支弹药相赠，只留下毛泽东的那件物品以示对英雄的敬重。
有可点击的【查看提示】按钮
获取提示： []
本题没有提示
暂时略过已达到 5 次，【 建议您将此题目的题干、提示、选项信息提交到github问题收集issue：https://github.com/TechXueXi/TechXueXi/issues/29 】
