### ISSUE TITLE
Docker中运行答题限入死循环

### ISSUE THREAD

**Issue by hnczj-twrbl** [TechXueXi/TechXueXi#38]
### 清单

- [x] 我已经仔细阅读过 README.md  (https://github.com/TechXueXi/TechXueXi/blob/master/README.md)
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [x] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**docker版本**：

-----

## 详细描述
答：Docker中运行答题时，如有两个选项有部分字符相同，程序限入死循环
![image](https://user-images.githubusercontent.com/59161588/131858528-a2f47a6b-eff7-4079-9df2-d2fb1ec72e68.png)

## 建议
答：上述情况时，让机器随机选择一项，这样可以完成答题，少几分可以接受。
     另外，如果是选择题，可以先判断题目中挖空的数量和答案数量是否相同，如果相同，直接全选就可以。无需查看提示

**Comment by qcwolf** [comment]
我视频答题也存在死循环问题，获取不到提示，然后一直重复，不能终止

![捕获](https://user-images.githubusercontent.com/22956195/132290135-349c32c2-e268-406c-bc5d-3a321ac8c9fb.PNG)

**Comment by grafspeecn** [comment]
和楼上一样，建议判断无提示的话直接跳过下一题

**Comment by lukemin** [comment]
![6CB25254](https://user-images.githubusercontent.com/12003375/133926794-59cedc93-f484-43f8-b363-a83e1615c75e.png)

**Comment by jifengmm** [comment]
老哥，群晖里面的卷那里，需要映射哪几个文件？

**Comment by lukemin** [comment]
不用映射文件啊，可以直接运行。

**Comment by lukemin** [comment]
看了一下日志，循环100次后，跳过了。

**Comment by QiuYueBaiJXW** [comment]
视频题希望可以乱答，不影响整体进程，实现无人值守

**Comment by techxuexi21** [comment]
现在可以在配置项设置循环次数，也计划使用题库解决
