### ISSUE TITLE
收不到二维码

### ISSUE THREAD

**Issue by tyf0628** [TechXueXi/TechXueXi#40]
### 清单

- [ ] 我已经仔细阅读过 README.md  (https://github.com/TechXueXi/TechXueXi/blob/master/README.md)
- [ ] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [ ] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com

**系统版本，包含位数**：CentOS Linux release 7.8.2003 (Core)

**软件/源码版本**：最新

**浏览器、驱动版本**：

**python版本**：

**docker版本**：

-----

## 详细描述
答：
收不到二维码。
已安装好学习强国最新版，设置好钉钉机器人后，只收到一条login url，点开后跳转到请下载手机客户端界面，再点击通过跳转打开苹果商店这款app，然后在商店内打开app就没了，最后docker 日志提示扫描二维码超时。

**Comment by techxuexi21** [comment]
Docker 如果发给你一个学习#国链接，不是让你下载，是让你登录，复制链接到学习#国app，发给某个人，比如自己，再点击链接
