### ISSUE TITLE
pushplus请求域名变化

### ISSUE THREAD

**Issue by wu5bocheng** [TechXueXi/TechXueXi#44]
### 清单

- [x] 我已经仔细阅读过 README.md  (https://github.com/TechXueXi/TechXueXi/blob/master/README.md)
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [x] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：centos7:amd64

**软件/源码版本**：amd64-master52

**浏览器、驱动版本**：chrome90.56.2763

**python版本**：python3.7.1

**docker版本**：not_known

-----

## 详细描述
答：pushplus服务请求域名变化为http://pushplus.hxtrip.com/,但代码未更新，导致一直返回token无效错误，错误代码999

## 全部报错
答：

```
私はChina を愛しています
```

## 建议
答：

**Comment by techxuexi21** [comment]
它官方有文件说明吗？
