### ISSUE TITLE
每周答题页面不能自动翻页

### ISSUE THREAD

**Issue by xwb2000** [TechXueXi/TechXueXi#48]
**系统版本，包含位数**：

**python版本**：

**软件/源码版本**：

**浏览器、驱动版本**：

-----

## 详细描述
答：每周答题的第一页全部答完之后不会自动翻页达到第二页，而是直接跳过
报非法错误
## 全部报错
答：

## 建议
答：

**Comment by ihahawen** [comment]
while (name_list[0] not in driver.page_source):
                try:
                    print('点击下一页')
                    driver.find_element_by_class_name("ant-pagination-next").click()
                    check_delay()
                    if("ant-pagination-disabled ant-pagination-next" in driver.page_source):
                        print("没有下一页按钮，跳出while循环")
                        break
                except Exception as e:
                    print('出错，在，跳出')
                    break
            print('进入下一结构')

**Comment by ihahawen** [comment]
我的解决方法是先判断当前页有没有可答的题目，没有就跳到下一页，跳到最后一页没有点击按钮了，就退出。

**Comment by xixihhhh** [comment]
我之前提了一个pr在dev分支，可以自动翻页

**Comment by CRISPRCas** [comment]
请问能合并一下这个分支吗，我看README上说“（如使用源码，请使用主分支。请勿使用 dev 分支，该分支仅用于同步开发）”

**Comment by TCPsoftware** [comment]
添加了自动翻页功能
