### ISSUE TITLE
Dock拉取命令不对

### ISSUE THREAD

**Issue by whuxxie** [TechXueXi/TechXueXi#48]
### 清单

- [* ] 我已经仔细阅读过 README.md  (https://github.com/TechXueXi/TechXueXi/blob/master/README.md)
- [* ] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [* ] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [ *] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：win10 64位

**软件/源码版本**：

**浏览器、驱动版本**：

**python版本**：

**docker版本**：

-----

## 详细描述
答：TechXueXi/DOCKER.md 文件中关于拉取的命令如下：
docker run -e "AccessToken={token}" -e "Secret={密钥}" -d --name={容器名称} techxuexi/techxuexi:{tag}
docker run -e "从Docker.md找到参数1" -e "从Docker.md找到参数2" -e "从Docker.md找到参数3" -d --name={容器名称} techxuexi/techxuexi:{tag}
下方备注：
请不要无脑照搬，需要修改

参数，输入时不输入{}

参数
tag=如果你是 amd64 的机器，那么就是 amd64，如果是 arm64 那么就是 arm64，然后后面跟版本号,例如 techxuexi/techxuexi:amd64-40 techxuexi/techxuexi:arm64-40

——————————————————————
其中tag表述不对，以备注中的写法无法获取，正确写法如下
techxuexi/techxuexi-amd64:dev53
注意短横线和冒号的位置

**Comment by techxuexi21** [comment]
谢谢，已注明
