### ISSUE TITLE
docker build时报错

### ISSUE THREAD

**Issue by xuhn** [TechXueXi/TechXueXi#55]
### 清单

- [x] 我已经仔细阅读过 README.md  (https://github.com/TechXueXi/TechXueXi/blob/master/README.md)
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [ ] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：
CentOS 7.4  x86_64
**软件/源码版本**：
dev分支
commit: 60650b368dbf10220939cce475815c5177960d66
**浏览器、驱动版本**：
无
**python版本**：
python3.6.8
**docker版本**：
docker 20.10.8
-----

## 详细描述
答：进行docker build时报错，镜像中libglib-2.0.so.0，libnss3.so找不到

## 全部报错
答：
1）
ESC[91m./chromedriver: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory
ESC[0mThe command '/bin/sh -c cd /xuexi/; wget -O chromedriver_linux64_75.0.3770.140.zip http://npm.taobao.org/mirrors/chromedriver/75.0.3770.140/chromedriver_linux64.zip; unzip chromedriver_linux64_75.0.3770.140.zip; chmod 755 chromedriver; ls -la; ./chromedriver --version' returned a non-zero code: 127

2）
./chromedriver: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

## 建议
答：Dockerfile中增加
apt-get install libglib2.0-0
apt-get install ibnss3-tools

**Comment by tchxiyi** [comment]
谢谢。但是我没有成功启动docker build

**Comment by techxuexi21** [comment]
已经成功运行，感谢建议。

**Comment by xuhn** [comment]
你好，我还是没有build成功，不仅仅是chromedriver，google-chrome75版本少的依赖太多了

**Comment by xuhn** [comment]
我看dev57的镜像里，chrome依赖是92版本的，并没有降级成75呀，Dockerfile好像不匹配吧

**Comment by xuhn** [comment]
这个Dockerfile我测过是可以build过的，但是依然没解决chrome在docker里crash的问题
FROM python:3.7-slim
ARG usebranche="dev"
ENV pullbranche=${usebranche}
RUN apt-get update
RUN apt-get install -y wget unzip libzbar0 git cron libglib2.0-0 libnss3-tools apt-transport-https ca-certificates curl gnupg --no-install-recommends
RUN curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update
RUN apt-get install -y google-chrome-stable fontconfig fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-symbola fonts-noto fonts-freefont-ttf --no-install-recommends
RUN apt-get purge --auto-remove -y curl gnupg
RUN rm -rf /var/lib/apt/lists/*
ENV TZ=Asia/Shanghai
ENV AccessToken=
ENV Secret=
ENV Nohead=True
ENV Pushmode=1
ENV islooplogin=False
ENV Sourcepath="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
ENV CRONTIME="30 9 * * *"
# RUN rm -f /xuexi/config/*; ls -la
COPY requirements.txt /xuexi/requirements.txt
COPY run.sh /xuexi/run.sh 
COPY start.sh /xuexi/start.sh 
RUN pip install -r /xuexi/requirements.txt
RUN cd /xuexi/; apt-get -fy install; google-chrome --version
RUN cd /xuexi/; wget https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip; unzip chromedriver_linux64.zip; chmod 755 chromedriver; ls -la; ./chromedriver --version

WORKDIR /xuexi
RUN chmod +x ./run.sh
RUN chmod +x ./start.sh
RUN mkdir code
WORKDIR /xuexi/code
RUN git clone -b ${pullbranche} ${Sourcepath}
WORKDIR /xuexi
ENTRYPOINT ["/bin/bash", "./start.sh"]

**Comment by xuhn** [comment]
chrome在docker里crash的问题可能和这个有关，我暂时这样改了没有再出现crash的现象
https://stackoverflow.com/questions/30210362/how-to-increase-the-size-of-the-dev-shm-in-docker-container
