### ISSUE TITLE
Dockerfile 问题建议

### ISSUE THREAD

**Issue by xuhn** [TechXueXi/TechXueXi#56]
### 清单

- [ ] 我已经仔细阅读过 README.md  (https://github.com/TechXueXi/TechXueXi/blob/master/README.md)
- [ ] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [ ] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [ ] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：

**软件/源码版本**：

**浏览器、驱动版本**：

**python版本**：

**docker版本**：

-----

## 详细描述
答：

## 全部报错
答：

我看dev57的镜像里，chrome依然是92版本的，并没有降级成75呀，Dockerfile好像不匹配吧
root@d2854a137e80:/xuexi# google-chrome -version
Google Chrome 92.0.4515.159

## 建议
答：
1、这个Dockerfile我测过是可以build过的，参考https://hub.docker.com/r/justinribeiro/chrome-headless/dockerfile/
FROM python:3.7-slim
ARG usebranche="dev"
ENV pullbranche=${usebranche}
RUN apt-get update
RUN apt-get install -y wget unzip libzbar0 git cron libglib2.0-0 libnss3-tools apt-transport-https ca-certificates curl gnupg --no-install-recommends
RUN curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update
RUN apt-get install -y google-chrome-stable fontconfig fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-symbola fonts-noto fonts-freefont-ttf --no-install-recommends
RUN apt-get purge --auto-remove -y curl gnupg
RUN rm -rf /var/lib/apt/lists/*
ENV TZ=Asia/Shanghai
ENV AccessToken=
ENV Secret=
ENV Nohead=True
ENV Pushmode=1
ENV islooplogin=False
ENV Sourcepath="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
ENV CRONTIME="30 9 * * *"

COPY requirements.txt /xuexi/requirements.txt
COPY run.sh /xuexi/run.sh
COPY start.sh /xuexi/start.sh
RUN pip install -r /xuexi/requirements.txt
RUN cd /xuexi/; apt-get -fy install; google-chrome --version
RUN cd /xuexi/; wget https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip; unzip chromedriver_linux64.zip; chmod 755 chromedriver; ls -la; ./chromedriver --version

WORKDIR /xuexi
RUN chmod +x ./run.sh
RUN chmod +x ./start.sh
RUN mkdir code
WORKDIR /xuexi/code
RUN git clone -b ${pullbranche} ${Sourcepath}
WORKDIR /xuexi
ENTRYPOINT ["/bin/bash", "./start.sh"]

2、chrome在docker里crash的问题可能和这个有关，我暂时这样改了没有再出现crash的现象
https://stackoverflow.com/questions/30210362/how-to-increase-the-size-of-the-dev-shm-in-docker-container

**Comment by techxuexi21** [comment]
好的。现在 dockerfile 回滚到使用 chrome92 的版本。之后是否升级，以后再看看吧
