### ISSUE TITLE
何时可以更新一下exe版，谢谢！

### ISSUE THREAD

**Issue by snakwu** [TechXueXi/TechXueXi#62]
希望可以用机器人，同步自动生成exe，谢谢！

**Comment by techxuexi21** [comment]
因为打包存在问题，长时间无法修复，以及打包后的文件一直报毒，以后不再提供win打包文件。

如果愿意协助，欢迎参与修复打包问题。  https://github.com/TechXueXi/TechXueXi/blob/dev/CONTRIBUTING.md

**Comment by snakwu** [comment]
打包报毒这个不是问题，相信的自然就会用！

**Comment by Orzyiii** [comment]
支持下
