### ISSUE TITLE
还是以前的打包版本好用  打开一个登录一个

### ISSUE THREAD

**Issue by Orzyiii** [TechXueXi/TechXueXi#77]
我是个小白  这个无头模式是个啥意思 我也不懂  就觉得 还是以前的好用

**Comment by gino1312** [comment]
Hehe

**Comment by Orzyiii** [comment]
那个&nbsp; t.me的地址&nbsp; 需要什么才能访问




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TechXueXi/TechXueXi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TechXueXi/TechXueXi] 还是以前的打包版本好用  打开一个登录一个 (Issue #77)





 
Closed #77.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by techxuexi21** [comment]
@Orzyiii https://github.com/bannedbook/fanqiang

https://github.com/gfw-breaker/nogfw

https://github.com/greatfire/wiki

**Comment by Orzyiii** [comment]
我进来了&nbsp; 谢谢&nbsp; 我手机越狱下载 vpn&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TechXueXi/TechXueXi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月23日(星期六) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TechXueXi/TechXueXi] 还是以前的打包版本好用  打开一个登录一个 (Issue #77)





 
@Orzyiii https://github.com/bannedbook/fanqiang
 
https://github.com/gfw-breaker/nogfw
 
https://github.com/greatfire/wiki
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
