### ISSUE TITLE
Mac 系统运行报错 ！！！！！

### ISSUE THREAD

**Issue by JLGB** [TechXueXi/TechXueXi#80]
运行命令后 python3 pandalearning.py，一直报库找不到，循环往复，一直这样

Unable to find zbar shared library
检测到你有python模块找不到，你可在搜索引擎搜索安装相关模块。
或转到上一级目录，运行：pip3 install -r requiremes.txt 或 pip install -r requirements.txt
下面为你尝试自动安装requirement.txt
如需自动安装按回车键继续...（如不需要自动尝试安装可现在关闭程序）

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: requests==2.26.0 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 1)) (2.26.0)
Requirement already satisfied: lxml==4.6.3 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 2)) (4.6.3)
Requirement already satisfied: colorama==0.4.1 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 3)) (0.4.1)
Requirement already satisfied: beautifulsoup4==4.9.3 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 4)) (4.9.3)
Requirement already satisfied: selenium==3.141.0 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 5)) (3.141.0)
Requirement already satisfied: pyhocon==0.3.58 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 6)) (0.3.58)
Requirement already satisfied: pyzbar==0.1.8 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 7)) (0.1.8)
Requirement already satisfied: pillow==8.2.0 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 8)) (8.2.0)
Requirement already satisfied: pyTelegramBotAPI==4.0.1 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 9)) (4.0.1)
Requirement already satisfied: gunicorn==20.1.0 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 10)) (20.1.0)
Requirement already satisfied: PySocks==1.7.1 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 11)) (1.7.1)
Requirement already satisfied: urllib3==1.26.7 in /usr/local/lib/python3.9/site-packages (from -r ../requirements.txt (line 12)) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/site-packages (from requests==2.26.0->-r ../requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/site-packages (from requests==2.26.0->-r ../requirements.txt (line 1)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/site-packages (from requests==2.26.0->-r ../requirements.txt (line 1)) (2020.12.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.9/site-packages (from beautifulsoup4==4.9.3->-r ../requirements.txt (line 4)) (2.2.1)
Requirement already satisfied: pyparsing>=2.0.3 in /usr/local/lib/python3.9/site-packages (from pyhocon==0.3.58->-r ../requirements.txt (line 6)) (2.4.7)
Requirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.9/site-packages (from gunicorn==20.1.0->-r ../requirements.txt (line 10)) (54.2.0)

自动安装完成，请重新运行程序
按回车键退出程序......

**Comment by azoth07** [comment]
运行 pip install -r requirements.txt
多看说明 please
https://github.com/TechXueXi/TechXueXi/blob/dev/%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95-%E6%9B%B4%E6%96%B0%E6%96%B9%E6%B3%95-%E4%B8%8B%E8%BD%BD%E6%96%B9%E5%BC%8F.md

**Comment by techxuexi21** [comment]
@JLGB 是这个问题 https://github.com/TechXueXi/TechXueXi/issues/50
