### ISSUE TITLE
session deleted because of page crash  from tab crashed。docker dev72 视频学习报异常

### ISSUE THREAD

**Issue by Lemon12148** [TechXueXi/TechXueXi#82]
### 清单

- [x] 我已经仔细阅读过 README.md  (https://github.com/TechXueXi/TechXueXi/blob/master/README.md)
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [ ] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

**系统版本，包含位数**：win10 64

**docker版本**：techxuexi/techxuexi-amd64:dev72

-----

## 详细描述
答：
docker 镜像版本 techxuexi/techxuexi-amd64:dev72
视频学习报错
![image](https://user-images.githubusercontent.com/23739639/138409347-1e1d392c-02c2-4799-8232-2301504057a7.png)

## 容器参数
![image](https://user-images.githubusercontent.com/23739639/138409805-9157791b-e50f-4d83-8fe6-cb26d1ff69d4.png)

## 全部报错
答：
```
视频学 xi 检测到异常：Message: unknown error: session deleted because of page crash

from tab crashed

  (Session info: headless chrome=92.0.4515.159)
```

**Comment by techxuexi21** [comment]
@Lemon12148 这个问题可能与以下有关：

1. 浏览器初始化参数
2. 浏览器新版（可能性低） 

这个 issue 也提到这个问题  https://github.com/TechXueXi/TechXueXi/issues/56

也有可能是其他原因。

希望同志们一起尝试解决

**Comment by azoth07** [comment]
有一种情况是/dev/shm太小了
docker-compose.yml 调整2gb
参考https://github.com/TechXueXi/TechXueXi/blob/dev/DOCKER.md

**Comment by Lemon12148** [comment]
更新了最新版本的docker tag后，暂时没有异常。

**Comment by Awei2020** [comment]
请问多账号钉钉推送，为什么第一个账号登录之后一直都是第一个账号了。其他的就不再让登录了

**Comment by techxuexi21** [comment]
@Awei2020 需要每次删除user文件夹来手动退出登录。可以远程运行命令

**Comment by hujingyu000** [comment]
0min扫描二维码超时，请问什么原因

**Comment by pili-book** [comment]
这docker不好使了吧？用别的去吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月21日(周日) 中午11:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [TechXueXi/TechXueXi] session deleted because of page crash  from tab crashed。docker dev72 视频学习报异常 (Issue #82)




 
0min扫描二维码超时，请问什么原因
