### ISSUE TITLE
钉钉无法找到Secret

### ISSUE THREAD

**Issue by liu-xinhui** [TechXueXi/TechXueXi#85]
### 清单

- [x] 我已经仔细阅读过 README.md  (https://github.com/TechXueXi/TechXueXi/blob/master/README.md)
- [x] 我已经查看/搜索过所有已有 issue，无论是open还是close的
- [x] 我已经通过搜索引擎搜索   www.google.com  www.baidu.com
- [x] 我已经到提供的在线聊天室询问过  (聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14)

![image](https://user-images.githubusercontent.com/7698511/138988122-e4c8537c-8cbe-48ad-a265-eb48777981d7.png)
![image](https://user-images.githubusercontent.com/7698511/138988136-7dc7c039-c0a3-4e95-b179-a279434053a8.png)

钉钉无法找到Secret在哪

**Comment by liu-xinhui** [comment]
![image](https://user-images.githubusercontent.com/7698511/138988550-94aec731-7fd6-4b13-8e07-61615e072200.png)
按照官网跳转后提示这个，但是我按照新版文档操作，没有secret

**Comment by npo5tech** [comment]
加签下面的输入框里，就是Secret

**Comment by liu-xinhui** [comment]
@npo5tech 可以了非常感谢
