### ISSUE TITLE
为什么1025版本没有“开始运行”这个文件？

### ISSUE THREAD

**Issue by BBSMLtd** [TechXueXi/TechXueXi#87]
**系统版本，包含位数**：win11 64位

**软件/源码版本**：1025

**浏览器、驱动版本**：edge 95.0.1020.30

**python版本**：3.8.6

**docker版本**：

为什么1025版本没有开始运行这个文件？1023也没有，只有1020版本才有吗？

- [ ] 

- [ ] 
![QQ截图20211027133501](https://user-images.githubusercontent.com/55902985/139006204-a28c9ca0-c1b9-4b79-827c-180cf96a58f8.png)

**Comment by techxuexi21** [comment]
@BBSMLtd 压缩包有两种。一个是完整包，现在没有最新完整包，一个只有源码。看文档：

    1. 下载包含python的windows完整压缩包，解压
    2. 下载最新源码（Assets 的 Source code (zip) ），解压，复制粘贴覆盖之前解压的旧文件  https://github.com/TechXueXi/TechXueXi/releases 
    3. 双击运行的文件开始运行。

没有问题的话点击最下面 close 关闭。

**Comment by BBSMLtd** [comment]
明白了，谢谢大佬

**Comment by xiaodaoaa** [comment]
> @BBSMLtd 压缩包有两种。一个是完整包，现在没有最新完整包，一个只有源码。看文档：
> 
> ```
> 1. 下载包含python的windows完整压缩包，解压
> 2. 下载最新源码（Assets 的 Source code (zip) ），解压，复制粘贴覆盖之前解压的旧文件  https://github.com/TechXueXi/TechXueXi/releases 
> 3. 双击运行的文件开始运行。
> ```
> 
> 没有问题的话点击最下面 close 关闭。

v20211025这样搞没问题，但是最新版的v20220126这样搞就不行，pillow=9.0.0安装错误，找不到该版本。

**Comment by 2020vae** [comment]
您好！已收到您的邮件，我会尽快查看的！！

**Comment by xiaodaoaa** [comment]
> 

v20211025这样搞没问题，但是最新版的v20220126这样搞就不行，pillow=9.0.0安装错误，找不到该版本。
![015](https://user-images.githubusercontent.com/45614322/157582511-5a0a4e4a-b834-42cc-9d72-1f4c0c8337b4.gif)

**Comment by xiaodaoaa** [comment]
> @BBSMLtd 压缩包有两种。一个是完整包，现在没有最新完整包，一个只有源码。看文档：
> 
> ```
> 1. 下载包含python的windows完整压缩包，解压
> 2. 下载最新源码（Assets 的 Source code (zip) ），解压，复制粘贴覆盖之前解压的旧文件  https://github.com/TechXueXi/TechXueXi/releases 
> 3. 双击运行的文件开始运行。
> ```
> 
> 没有问题的话点击最下面 close 关闭。

v20211025这样搞没问题，但是最新版的v20220126这样搞就不行，pillow=9.0.0安装错误，找不到该版本。
![image](https://user-images.githubusercontent.com/45614322/157582672-ab662a05-854c-4b49-88db-35e5db010bda.png)

**Comment by 2020vae** [comment]
您好！已收到您的邮件，我会尽快查看的！！
